#!/usr/bin/python2

import sys

from ai_import.init import connect
from ai_import.init import getArgs
from ai_import.trantorian import Trantorian
from ai_import.IA import IA

def main(argv):
    client = getArgs(argv)
    sock = connect(client)
    player = Trantorian(client, sock)
    if not player.introduce():
        return
    IA(player)

if __name__ == "__main__":
    main(sys.argv[1:])
